// src/components/FilterBar.jsx
// TODO: Should we use nanostores
import { CurrentFilter, SortBy, DisplayStyle } from './filter.js';
import { useStore } from '@nanostores/react';
import Button from 'react-bootstrap/Button';
import ButtonGroup from 'react-bootstrap/ButtonGroup';
import Form from 'react-bootstrap/Form';
import ToggleButton from 'react-bootstrap/ToggleButton';
import ToggleButtonGroup from 'react-bootstrap/ToggleButtonGroup';

// A react component class with a search box and button groups for filtering and sorting
export default function FilterBar(input) {
    const currentFilter = useStore(CurrentFilter);
    const sortBy = useStore(SortBy);
    const displayStyle = useStore(DisplayStyle);
    // const [displayStyle, setDisplayStyle] = useStore(DisplayStyle);

    const updateFilter = (event) => {
        let newFilter = currentFilter;
        if (newFilter.includes(event.target.value)) {
            newFilter = newFilter.filter((filter) => filter !== event.target.value);
        } else {
            newFilter.push(event.target.value);
        }
        CurrentFilter.set(newFilter);
        console.log(CurrentFilter);
    };

    const updateSortBy = (event) => {
        console.log(event.target.value);
        console.log(sortBy);
        sortBy.set(event.target.value);
    };

    const updateDisplayStyle = (event) => {
        displayStyle.set(event.target.value);
    };
    const num_released = input.input.filter(
        (pipeline) => pipeline.releases.length > 0 && pipeline.archived !== true
    ).length;
    const num_dev = input.input.filter((pipeline) => pipeline.releases.length === 0).length;
    const num_archived = input.input.filter((pipeline) => pipeline.archived === true).length;
    const filters = [
        { name: 'Released', count: num_released, active: currentFilter.includes('released') },
        { name: 'Under development', count: num_dev, active: currentFilter.includes('under_development') },
        { name: 'Archived', count: num_archived, active: currentFilter.includes('archived') },
    ];
    const sorts = [{ name: 'Last release' }, { name: 'Alphabetical' }, { name: 'Stars', active: sortBy === 'stars' }];
    return (
        <div className="filter-bar">
            <div className="d-md-none dropdown">
                <button
                    className="btn btn-secondary dropdown-toggle"
                    type="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                >
                    Filter & Sort
                </button>
                <div className="dropdown-menu">
                    <Form.Control className="searchbox" type="text" placeholder="Search keywords" />
                    <div className="me-2 d-flex flex-column">
                        Filter:
                        <ButtonGroup className="ms-1">
                            {filters.map((filter) => (
                                <Button
                                    variant="outline-success"
                                    className={
                                        'text-nowrap' +
                                        (currentFilter.includes(filter.name.toLowerCase().replace(' ', '_'))
                                            ? ' active'
                                            : '')
                                    }
                                    value={filter.name.toLowerCase().replace(' ', '_')}
                                    onClick={updateFilter}
                                >
                                    {filter.name} <span className="badge bg-secondary">{filter.count}</span>
                                </Button>
                            ))}
                        </ButtonGroup>
                    </div>
                    <div className="me-2 d-flex flex-column">
                        Sort:
                        <ButtonGroup className="ms-1">
                            {sorts.map((sort) => (
                                <ToggleButton
                                    variant="outline-success"
                                    type="radio"
                                    name="radio"
                                    value={sort.name}
                                    checked={sort.active}
                                    className="text-nowrap"
                                >
                                    {sort.name}
                                </ToggleButton>
                            ))}
                        </ButtonGroup>
                    </div>
                    <div className="me-2 d-flex flex-column">
                        Display:
                        <ButtonGroup className="ms-1">
                            <Button
                                variant="outline-success"
                                data-bs-toggle="tooltip"
                                data-bs-title="Display as cards"
                                className={displayStyle === 'grid' ? 'active' : ''}
                                onChange={updateDisplayStyle}
                            >
                                <i className="fa-regular fa-grid-2"></i>
                            </Button>
                            <Button
                                variant="outline-success"
                                data-bs-toggle="tooltip"
                                data-bs-title="Display as table"
                                className={displayStyle === 'table' ? 'active' : ''}
                                onChange={updateDisplayStyle}
                            >
                                <i className="fas fa-bars"></i>
                            </Button>
                        </ButtonGroup>
                    </div>
                </div>
            </div>

            <div className="d-none d-md-flex sticky-top justify-content-start">
                <Form.Control className="searchbox" type="text" placeholder="Search keywords" />
                <div className="d-flex align-items-center ms-3">
                    Filter:
                    <ButtonGroup className="ms-1">
                        {filters.map((filter) => (
                            <Button
                                variant="outline-success"
                                value={filter.name.toLowerCase().replace(' ', '_')}
                                className={
                                    'text-nowrap' +
                                    (currentFilter.includes(filter.name.toLowerCase().replace(' ', '_'))
                                        ? ' active'
                                        : '')
                                }
                                onClick={updateFilter}
                            >
                                {filter.name} <span className="badge bg-secondary">{filter.count}</span>
                            </Button>
                        ))}
                    </ButtonGroup>
                </div>
                <div className="d-flex align-items-center ms-3">
                    Sort:
                    <ToggleButtonGroup type="radio" name="options" defaultValue={sortBy} className="ms-1">
                        {sorts.map((sort) => (
                            <ToggleButton
                                variant="outline-success text-nowrap"
                                type="radio"
                                name="radio"
                                value={sort.name.toLowerCase().replace(' ', '_')}
                                className=""
                                onClick={updateSortBy}
                            >
                                {sort.name}
                            </ToggleButton>
                        ))}
                    </ToggleButtonGroup>
                </div>
                <div className="d-flex align-items-center ms-3">
                    Display:
                    <ButtonGroup className="ms-1">
                        <ToggleButton
                            variant="outline-success"
                            data-bs-toggle="tooltip"
                            data-bs-title="Display as cards"
                            className={displayStyle === 'grid' ? 'active' : ''}
                            type="radio"
                            name="radio"
                            checked={displayStyle === 'grid'}
                            onClick={updateDisplayStyle}
                        >
                            <i className="fa-regular fa-grid-2"></i>
                        </ToggleButton>
                        <ToggleButton
                            variant="outline-success"
                            data-bs-toggle="tooltip"
                            data-bs-title="Display as table"
                            className={displayStyle === 'table' ? 'active' : ''}
                            type="radio"
                            name="radio"
                            checked={displayStyle === 'table'}
                            onClick={updateDisplayStyle}
                        >
                            <i className="fas fa-bars"></i>
                        </ToggleButton>
                    </ButtonGroup>
                </div>
            </div>
        </div>
    );
}

// sites/main-site/src/components/FilterBar.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { CurrentFilter, Filters, SortBy, DisplayStyle, SearchQuery } from "@components/store";

    interface FilterItem {
        name: string;
        displayName?: string;
        class?: string;
        icon?: string;
        count?: number;
    }

    let {
        filter = [],
        sortBy = [],
        displayStyle = [],
        filterName = () => "Status",
    } = $props<{
        filter: FilterItem[];
        sortBy: string[];
        displayStyle: { name: string; icon: string }[];
        filterName?: () => string;
    }>();
    // Initialize filters once on mount
    onMount(async () => {
        // Reset stores if no filters provided
        if (filter.length === 0) {
            Filters.set([]);
            CurrentFilter.set([]);
        } else {
            Filters.set(filter);
        }

        // Reset sort if no options provided
        if (sortBy.length === 0) {
            SortBy.set("");
        } else if (!$SortBy) {
            SortBy.set(sortBy[0]);
        }

        // Reset display style if no options provided
        if (displayStyle.length === 0) {
            DisplayStyle.set("grid");
        }

        // Always reset search
        SearchQuery.set("");
    });

    let search = $state($SearchQuery);

    function handleSearch(q: Event) {
        const target = q.target as HTMLInputElement;
        SearchQuery.set(target.value.trim());
    }

    function handleFilter(fil: string, e: Event) {
        e.preventDefault();
        // remove focus from button
        (e.target as HTMLElement).blur();

        const newFilters = $CurrentFilter.some((f) => f.name === fil)
            ? $CurrentFilter.filter((f) => f.name !== fil)
            : [...$CurrentFilter, { name: fil }];

        CurrentFilter.set(newFilters);
    }

    function handleExclusiveFilter(fil: string, e: Event) {
        e.preventDefault();
        // remove focus from button
        (e.target as HTMLElement).blur();
        CurrentFilter.set([{ name: fil }]);
    }

    function handleSort(sor: string) {
        SortBy.set(sor);
    }

    function handleDisplayStyle(style: string) {
        DisplayStyle.set(style);
    }
</script>

<div class="filter-bar mb-2 px-2">
    <div class="d-flex w-100 justify-content-between justify-content-md-center">
        <input
            type="text"
            class="form-control w-25 me-2 searchbar"
            value={search}
            oninput={handleSearch}
            placeholder="Search"
        />

        <div class="d-none d-xl-block ms-3 d-flex align-items-center">
            <div class="btn-group ms-1 filter-buttons d-flex" role="group" aria-label="Filter listing">
                {#each $Filters as fil}
                    <button
                        type="button"
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        data-bs-delay="500"
                        title="Double click to only show items from this category"
                        class={fil.class
                            ? "btn text-nowrap flex-fill btn-outline-" + fil.class
                            : "btn text-nowrap w-100 btn-outline-success"}
                        class:active={$CurrentFilter.some((f) => f.name === fil.name)}
                        onclick={(e) => handleFilter(fil.name, e)}
                        ondblclick={(e) => handleExclusiveFilter(fil.name, e)}
                    >
                        {#if fil.icon}
                            <i class={fil.icon + " me-1"}></i>
                        {/if}
                        {fil.displayName || fil.name}
                        {#if fil.count !== undefined && fil.count >= 0}
                            <span class="badge bg-secondary ms-1">{fil.count}</span>
                        {/if}
                    </button>
                {/each}
            </div>
        </div>
        <div class="d-xl-none ms-1 ms-md-3 align-items-center">
            <div class="dropdown">
                <button
                    class="btn btn-outline-success dropdown-toggle text-nowrap"
                    type="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                >
                    {filterName()}
                </button>
                <ul class="dropdown-menu">
                    {#each $Filters as fil}
                        <li>
                            <div
                                class="dropdown-item"
                                title="Filter"
                                class:active={$CurrentFilter.some((f) => f.name === fil.name)}
                                onclick={(e) => handleFilter(fil.name, e)}
                                onkeydown={(e) => e.key === "Enter" && handleFilter(fil.name, e)}
                                role="button"
                                tabindex="0"
                            >
                                {#if fil.icon}
                                    <i class={fil.icon + " fa-fw me-1"}></i>
                                {/if}
                                {fil.displayName || fil.name}
                                {#if fil.count !== undefined && fil.count >= 0}
                                    <span class="badge bg-secondary ms-1">{fil.count}</span>
                                {/if}
                            </div>
                        </li>
                    {/each}
                </ul>
            </div>
        </div>
        {#if sortBy.length > 1}
            <div class="ms-1 ms-md-3 align-items-center">
                <div class="dropdown">
                    <button
                        class="btn btn-outline-success dropdown-toggle text-nowrap"
                        type="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        <i class="fa-solid fa-arrow-down-wide-short me-1"></i>
                        <span class="d-none d-md-inline">{$SortBy}</span>
                    </button>
                    <ul class="dropdown-menu">
                        {#each sortBy as sor (sor)}
                            <li>
                                <div
                                    class="dropdown-item"
                                    title="sort"
                                    id={sor.replace(" ", "-")}
                                    class:active={sor === $SortBy}
                                    onclick={(e) => handleSort(sor)}
                                    onkeydown={(e) => handleSort(sor)}
                                    role="button"
                                    tabindex="0"
                                >
                                    {sor}
                                </div>
                            </li>
                        {/each}
                    </ul>
                </div>
            </div>
        {/if}
        {#if displayStyle.length > 1}
            <div class="ms-1 ms-md-3 d-flex align-items-center">
                <div class="btn-group ms-1 display-buttons" role="group" aria-label="Display style">
                    {#each displayStyle as dis}
                        <button
                            type="button"
                            class="btn btn-outline-success text-nowrap"
                            onclick={(e) => handleDisplayStyle(dis.name)}
                            class:active={$DisplayStyle === dis.name}
                            title={dis.name + " view"}
                            data-bs-toggle="tooltip"
                            aria-label={dis.name + " view"}
                            ><i class={dis.icon}></i>
                        </button>
                    {/each}
                </div>
            </div>
        {/if}
    </div>
</div>
